# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import calc as module_0


def test_case_0():
    bytes_0 = b"\xe7,"
    var_0 = module_0.add2(bytes_0, bytes_0)
    assert var_0 == "b'\\xe7,'b'\\xe7,'"


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = '@N\x0cSSX/8"tqQb(b;Dg'
    dict_0 = {str_0: str_0}
    module_0.conv(dict_0)


def test_case_2():
    bool_0 = False
    var_0 = module_0.add2(bool_0, bool_0)
    assert var_0 == 0


def test_case_3():
    bool_0 = False
    var_0 = module_0.conv(bool_0)


def test_case_4():
    int_0 = 4810
    var_0 = module_0.add2(int_0, int_0)
    assert var_0 == 9620
    bytes_0 = b"\xe7,"
    var_1 = module_0.add2(bytes_0, bytes_0)
    assert var_1 == "b'\\xe7,'b'\\xe7,'"
    bytes_1 = b"\xd0\x12\xfe\x9b\xb87"
    var_2 = module_0.conv(var_0)
    assert var_2 == 9620
    var_3 = module_0.conv(var_0)
    assert var_3 == 9620
    var_4 = module_0.add2(var_2, var_1)
    assert var_4 == "9620b'\\xe7,'b'\\xe7,'"
    var_5 = module_0.conv(bytes_1)
    var_6 = module_0.add2(var_0, var_4)
    var_7 = module_0.conv(bytes_0)
    var_8 = module_0.conv(var_3)
